kind: Service
apiVersion: v1
metadata:
  name: prophet
  namespace: {{ .Chart.Name }}
  labels:
    environment: {{ .Values.environment }}
    service: {{ .Chart.Name }}
    type: prophet
spec:
  selector:
    app: prophet
  ports:
    - protocol: TCP
      port: 9090
      targetPort: prophet-port
